import math
import unittest

from config import CameraConfig
from datatypes import TargetEstimate
from perception.geometry import CameraModel
from tools.calibrate_camera import (
    aspect_from_frame_shape,
    compute_fov,
    report,
    size_frac_from_points,
)


class SizeFracFromPoints(unittest.TestCase):
    def test_measures_vertical_pixel_gap_as_a_fraction_of_frame_height(self):
        # 100px tall object in a 400px-tall frame -> 0.25
        self.assertAlmostEqual(size_frac_from_points((10, 50), (10, 150), 400), 0.25)

    def test_order_of_the_two_points_does_not_matter(self):
        a = size_frac_from_points((0, 50), (0, 150), 400)
        b = size_frac_from_points((0, 150), (0, 50), 400)
        self.assertAlmostEqual(a, b)

    def test_horizontal_position_is_irrelevant(self):
        a = size_frac_from_points((0, 50), (0, 150), 400)
        b = size_frac_from_points((999, 50), (999, 150), 400)
        self.assertAlmostEqual(a, b)

    def test_identical_points_is_an_error_not_a_silent_zero(self):
        with self.assertRaises(ValueError):
            size_frac_from_points((5, 50), (5, 50), 400)

    def test_zero_frame_height_is_an_error(self):
        with self.assertRaises(ValueError):
            size_frac_from_points((5, 0), (5, 10), 0)


class AspectFromFrameShape(unittest.TestCase):
    def test_matches_cameraconfig_convention_height_over_width(self):
        # 480 tall, 640 wide -> 0.75, same as CameraConfig's documented 4:3 default
        self.assertAlmostEqual(aspect_from_frame_shape((480, 640)), 0.75)

    def test_rejects_degenerate_shapes(self):
        with self.assertRaises(ValueError):
            aspect_from_frame_shape((0, 640))
        with self.assertRaises(ValueError):
            aspect_from_frame_shape((480, 0))


class ComputeFovValidation(unittest.TestCase):
    def test_rejects_non_positive_inputs(self):
        with self.assertRaises(ValueError):
            compute_fov(0, 0.22, 0.3, 0.75)
        with self.assertRaises(ValueError):
            compute_fov(2.0, 0, 0.3, 0.75)
        with self.assertRaises(ValueError):
            compute_fov(2.0, 0.22, 0, 0.75)
        with self.assertRaises(ValueError):
            compute_fov(2.0, 0.22, 1.5, 0.75)
        with self.assertRaises(ValueError):
            compute_fov(2.0, 0.22, 0.3, 0)


class ComputeFovRoundTrip(unittest.TestCase):
    """The real check: feed compute_fov() a size_frac generated by
    perception/geometry.py's own CameraModel for a KNOWN hfov/aspect, and
    confirm it recovers that same hfov/aspect. This is the actual inverse
    relationship the calibration tool depends on -- not just a hand-picked
    example."""

    def round_trip(self, hfov_deg, aspect, face_height_m, distance_m):
        cfg = CameraConfig(hfov_deg=hfov_deg, aspect=aspect, face_height_m=face_height_m)
        model = CameraModel(cfg)
        # What the camera would report for a face-height object at distance_m,
        # centred (offset_x = offset_y = 0) -- locate()/project() aren't needed,
        # size_at_1m already IS "size at 1 metre", so size at distance_m is:
        size_frac = model.size_at_1m / distance_m
        got_hfov, got_vfov = compute_fov(distance_m, face_height_m, size_frac, aspect)
        self.assertAlmostEqual(got_hfov, hfov_deg, places=6)
        self.assertAlmostEqual(got_vfov, math.degrees(2 * math.atan(model.tan_v)), places=6)

    def test_default_camera_config(self):
        self.round_trip(hfov_deg=66.0, aspect=0.75, face_height_m=0.22, distance_m=2.5)

    def test_wide_laptop_webcam_like_fov(self):
        self.round_trip(hfov_deg=78.0, aspect=9 / 16, face_height_m=0.22, distance_m=1.0)

    def test_narrow_telephoto_like_fov(self):
        self.round_trip(hfov_deg=35.0, aspect=0.75, face_height_m=0.297, distance_m=5.0)

    def test_close_and_far_distances_agree_on_the_same_fov(self):
        near = None
        for distance_m in (0.5, 1.0, 3.0, 10.0):
            cfg = CameraConfig(hfov_deg=60.0, aspect=0.75, face_height_m=0.22)
            model = CameraModel(cfg)
            size_frac = model.size_at_1m / distance_m
            hfov, _ = compute_fov(distance_m, cfg.face_height_m, size_frac, cfg.aspect)
            if near is None:
                near = hfov
            else:
                self.assertAlmostEqual(hfov, near, places=6)


class ReportText(unittest.TestCase):
    def test_includes_both_measurements_and_the_main_py_flag(self):
        text = report(70.0, 55.0, 0.75)
        self.assertIn("70.0", text)
        self.assertIn("aspect", text)
        self.assertIn("--hfov 70.0", text)

    def test_flags_a_large_difference_from_the_current_default(self):
        text = report(70.0, 55.0, 0.75, current=CameraConfig(hfov_deg=66.0))
        self.assertNotIn("Note:", text)  # only 4 deg off -- not worth flagging
        text2 = report(90.0, 60.0, 0.75, current=CameraConfig(hfov_deg=66.0))
        self.assertIn("Note:", text2)


if __name__ == "__main__":
    unittest.main()
